using System.Collections.Generic;
using Meadow.Scaffolding.Models;

namespace Meadow.Scaffolding.Extensions;

public static class ProcessedTypeExtensions
{

    public static bool IsIdAutoGenerated(this ProcessedType processedType)
    {
        return processedType.HasId && processedType.IdField.IsAutoValued;
    }
    
    public static List<Parameter> GetInsertParameters(this ProcessedType processedType)
    {
        return IsIdAutoGenerated(processedType)
            ? processedType.NoneIdParameters
            : processedType.Parameters;
    }
}