using Acidmanic.Utilities.Extensions;
using Acidmanic.Utilities.Reflection.Attributes;
using Meadow.Attributes;
using Meadow.Configuration;
using Meadow.DataAccessResolving;
using Meadow.MySql;
using Meadow.Scaffolding.Snippets;
using Meadow.Utility;

namespace Meadow.Test.Unit;

public class TranslationTests
{

    
    [EventStreamSerializationCompression(Compressions.GZip)]
    [EventStreamPreferences(typeof(Guid), typeof(long))]
    public interface IStatisticsEvent
    {
        [UniqueMember]
        public long Id { get; set; }
    
    }

    [Fact]
    public void ShouldReturn_Correct_Table_For_EventStream()
    {

        var configuration = MeadowConfiguration.Null;
        MeadowEngine.UseDataAccess(new CoreProvider<MySqlDataAccessCore>());
        var resolver = new DataAccessServiceResolver(configuration);
        var translator = resolver.SqlTranslator;

        var builder = new  ParameterBuilder(resolver.DbTypeNameMapper);

        builder.Name("A")
            .AutoGenerated()
            .Unique()
            .Type<Guid>();


        var definition = translator.TableColumnDefinition(builder.Build().First());

    }
}