using Meadow.Scaffolding.Attributes;
using Meadow.Scaffolding.Extensions;
using Meadow.Scaffolding.Snippets;
using Meadow.Scaffolding.Snippets.Builtin;

namespace Meadow.SQLite.Snippets;

[CommonSnippet(CommonSnippets.InsertProcedure)]
public class InsertSnippet : ISnippet
{
    public SnippetToolbox Toolbox { get; set; } = SnippetToolbox.Null;

    public string KeyHeaderCreation => Toolbox.SqlTranslator.CreateProcedurePhrase(Toolbox.Configurations.RepetitionHandling,
        Toolbox.ProcessedType.NameConvention.InsertProcedureName);

    public string KeyParameters => Toolbox.GetProcedureDefinitionParameters();
    public string KeyTableName => Toolbox.ProcessedType.NameConvention.TableName;
    public string KeyInsertColumns => Toolbox.GetNoneAutoGeneratedColumns();
    public string KeyInsertValues => Toolbox.GetNoneAutoGeneratedValues();
    public string KeyEntityFilterSegment => Toolbox.GetEntityFiltersWhereClause(" AND ", " ");


    public ISnippet Line => new CommentLineSnippet();

    public string Template => @"
{KeyHeaderCreation}({KeyParameters}) AS
    INSERT INTO {KeyTableName} ({KeyInsertColumns})
    VALUES ({KeyInsertValues});
    SELECT * FROM {KeyTableName} WHERE ROWID=LAST_INSERT_ROWID(){KeyEntityFilterSegment};
GO
{Line}
".Trim();
}