using System;
using Meadow.Scaffolding.Attributes;
using Meadow.Scaffolding.Extensions;
using Meadow.Scaffolding.Snippets;

namespace Meadow.SQLite.Snippets;

[CommonSnippet(CommonSnippets.UpdateProcedure)]
public class UpdateSnippet:ISnippet
{
    public ISnippetToolbox Toolbox { get; set; } = SnippetToolbox.Null;

    public string ProcedureDefinition => Toolbox.SqlTranslator.CreateProcedurePhrase(Toolbox.Configurations.RepetitionHandling,
        Toolbox.ProcessedType.NameConvention.UpdateProcedureName);

    public string TableName => Toolbox.ProcessedType.NameConvention.TableName;

    public string KeyNoneIdParametersSet => Toolbox.GetNoneAutoGeneratedSets();
    
    public string KeyEntityFilterSegment => Toolbox.GetEntityFiltersWhereClause(" AND "," ");

    public string KeyIdFieldName => Toolbox.ProcessedType.HasId? Toolbox.ProcessedType.IdParameter.Name:string.Empty;

    public string Procedure(string body) => Toolbox.Procedure(
        Toolbox.Configurations.RepetitionHandling,
        Toolbox.ProcessedType.NameConvention.UpdateProcedureName,
        body, string.Empty,Toolbox.ProcessedType.NameConvention.TableName,
        Toolbox.ProcessedType.Parameters.ToArray());
    
    public string Template => @"
{Procedure}
    UPDATE {TableName} SET {KeyNoneIdParametersSet} WHERE {TableName}.{KeyIdFieldName}=@{KeyIdFieldName}{KeyEntityFilterSegment};
    SELECT * FROM {TableName} WHERE {TableName}.{KeyIdFieldName}=@{KeyIdFieldName}{KeyEntityFilterSegment};
{/Procedure}
".Trim();
}