using System;
using Meadow.Scaffolding.Attributes;
using Meadow.Scaffolding.Extensions;
using Meadow.Scaffolding.Snippets;

namespace Meadow.SQLite.Snippets;

[CommonSnippet(CommonSnippets.UpdateProcedure)]
public class UpdateSnippet:ISnippet
{
    public SnippetToolbox Toolbox { get; set; } = SnippetToolbox.Null;

    public string DefinitionParameters => Toolbox.GetProcedureDefinitionParameters();

    public string ProcedureDefinition => Toolbox.SqlTranslator.CreateProcedurePhrase(Toolbox.Configurations.RepetitionHandling,
        Toolbox.ProcessedType.NameConvention.UpdateProcedureName);

    public string TableName => Toolbox.ProcessedType.NameConvention.TableName;

    public string KeyNoneIdParametersSet => Toolbox.GetNoneAutoGeneratedSets();
    
    public string KeyEntityFilterSegment => Toolbox.GetEntityFiltersWhereClause(" AND "," ");

    public string KeyIdFieldName => Toolbox.ProcessedType.HasId? Toolbox.ProcessedType.IdParameter.Name:string.Empty;
    
    public string Template => @"
{ProcedureDefinition} ({DefinitionParameters}) AS

    UPDATE {TableName} SET {KeyNoneIdParametersSet} WHERE {TableName}.{KeyIdFieldName}=@{KeyIdFieldName}{KeyEntityFilterSegment};
    SELECT * FROM {TableName} WHERE {TableName}.{KeyIdFieldName}=@{KeyIdFieldName}{KeyEntityFilterSegment};
GO
".Trim();
}