using System;
using System.Collections.Generic;
using Acidmanic.Utilities.Reflection.ObjectTree;
using Meadow.Contracts;
using Meadow.Scaffolding.Attributes;

namespace Meadow.Scaffolding.Models
{
    /// <summary>
    /// This class would contain common information that might be needed for generating scripts. 
    /// </summary>
    public class ProcessedType
    {

        public static readonly ProcessedType Null = new();
        
        public RecordIdentificationProfile RecordIdentificationProfile { get; set; } = new();
        
        public List<Parameter> Parameters { get; set; } = new();

        public List<Parameter> NoneIdParameters { get; set; } = new();

        public List<Parameter> NoneIdUniqueParameters { get; set; } = new();

        public Parameter IdParameter { get; set; } = Parameter.Null;
        
        public List<Parameter> ParametersFullTree { get; set; } = new List<Parameter>();

        [Obsolete]
        // ReSharper disable once CollectionNeverQueried.Global
        public List<Parameter> NoneIdParametersFullTree { get; set; } = new();
        [Obsolete]
        // ReSharper disable once CollectionNeverQueried.Global
        public List<Parameter> NoneIdUniqueParametersFullTree { get; set; } = new List<Parameter>();

        public Parameter IdParameterFullTree { get; set; } = Parameter.Null;

        public NameConvention NameConvention { get; set; } =NameConvention.Null;

        public AccessNode? IdField { get; set; } = null;

        public bool HasId { get; set; } = false;


        public bool IsStreamEvent { get; set; } = false;

        public EventStreamPreferencesInfo? EventStream { get; set; }

        public string? EventIdTypeName { get; set; }
        
        public Type? EventIdType { get; set; }

        public string? StreamIdTypeName { get; set; }

        public string? EventStreamTypeNameDatabaseType { get; set; }
        
        public string? EventStreamAssemblyNameDatabaseType { get; set; }

        public string? EventStreamSerializedValueDatabaseType { get; set; }

        public bool IsEventIdAutogenerated { get; set; }
        
        
        public Parameter IndexCorpusParameter { get; set; } = Parameter.Null;

        public Dictionary<string, string> SaveProcedureNames { get; set; } = new();
    }
}