using System.Linq;
using Acidmanic.Utilities.Reflection;
using Acidmanic.Utilities.Reflection.FieldInclusion;
using Meadow.Extensions;

namespace Meadow.Requests.BuiltIn
{
    public sealed class InsertRequest<T> : MeadowRequest<T, T> where T : class
    {
        public InsertRequest(T model) : base(true)
        {
            ToStorage = model;
        }

        protected override void OnFieldManipulation(IFieldInclusionMarker toStorage,
            IFieldInclusionMarker fromStorage)
        {
            base.OnFieldManipulation(toStorage, fromStorage);

            var idLeaf = TypeIdentity.GetAutoGeneratedLeaves<T>().FirstOrDefault();
            
            if (idLeaf != null)
            {
                toStorage.Exclude(idLeaf.GetFullName());
            }
        }

        public override string RequestText
        {
            get
            {
                var nc = Configuration.GetNameConvention<T>();

                return nc.InsertProcedureName;
            }
        }
    }
}