using System;
using Meadow.Contracts;
using Meadow.DataTypeMapping;
using Meadow.Scaffolding.Models;
using Meadow.Utility;

namespace Meadow.Scaffolding.Snippets;

public interface IParameterBuilder<TSelf>
{
    TSelf Name(string name);
    TSelf Type(string typeName, bool isNumerical = false);
    TSelf Type(Type type);
    TSelf Unique();
    TSelf Unique(bool isUnique);
    TSelf AutoGenerated();
    TSelf AutoGenerated(bool isAutoGenerated);
    TSelf Type<T>();
}

public interface IParameterBuilder:IParameterBuilder<IParameterBuilder>
{
    
}

public class ParameterBuilder : ParameterBuilder<IParameterBuilder>
{
    public ParameterBuilder(IDbTypeNameMapper dbTypeNameMapper) : base(dbTypeNameMapper)
    {
    }
}

public class ParameterBuilder<TInterface>:IParameterBuilder<TInterface>
where TInterface:IParameterBuilder<TInterface>
{
    private readonly IDbTypeNameMapper _dbTypeNameMapper;

    private string _name = "Parameter";
    private string _standardName = "Model.Parameter";
    private string _typeName = "string";
    private bool _isNumerical = false;
    private bool _isUnique = false;
    private bool _isAutoGenerated = false;


    public ParameterBuilder(IDbTypeNameMapper dbTypeNameMapper)
    {
        _dbTypeNameMapper = dbTypeNameMapper;
        _typeName = dbTypeNameMapper.GetDatabaseTypeName(typeof(string));
    }

    public TInterface Name(string name)
    {
        _name = name;

        _standardName = "Model." + name;

        return this;
    }


    public TInterface Type(string typeName, bool isNumerical = false)
    {
        _typeName = typeName;

        _isNumerical = isNumerical;

        return this;
    }

    public TInterface Type(Type type)
    {
        _typeName = _dbTypeNameMapper.GetDatabaseTypeName(type);

        _isNumerical = EntityTypeUtilities.IsNumeric(type);

        return this;
    }

    public TInterface Unique()
    {
        _isUnique = true;

        return this;
    }

    public TInterface Unique(bool isUnique)
    {
        _isUnique = isUnique;

        return this;
    }

    public TInterface AutoGenerated() => AutoGenerated(true);

    public TInterface AutoGenerated(bool isAutoGenerated)
    {
        _isAutoGenerated = isAutoGenerated;

        return this;
    }


    public TInterface Type<T>() => Type(typeof(T));


    public Parameter Build()
    {
        var parameter = new Parameter
        {
            Name = _name,
            IdentifierStatus = ParameterIdentifierStatus.None,
            IsNumerical = _isNumerical,
            StandardAddress = _standardName,
            Type = _typeName
        };

        if (_isUnique) parameter.IdentifierStatus |= ParameterIdentifierStatus.Unique;
        if (_isAutoGenerated) parameter.IdentifierStatus |= ParameterIdentifierStatus.AutoGenerated;

        return parameter;
    }
}