using System;

namespace Meadow.DataTypeMapping
{
    public class FieldType
    {
        public Type Type { get; set; }
        
        public string DbTypeName { get; set; }

        public bool IsAutoGenerated { get; set; }
    }
}