using System;
using Acidmanic.Utilities.Reflection;

namespace Meadow.DataTypeMapping
{
    public class FieldType
    {
        private readonly static Type[] NumericTypes =
        {
            typeof(byte),
            typeof(sbyte),
            typeof(short),
            typeof(ushort),
            typeof(float),
            typeof(double),
            typeof(decimal),
            typeof(long),
            typeof(ulong),
            typeof(int),
        };
        public Type Type { get; set; }
        
        public string DbTypeName { get; set; }

        public bool IsAutoGenerated { get; set; }
        
        public string ColumnName { get; set; }

        public bool IsNumeric()
        {
            foreach (var numericType in NumericTypes)
            {
                if (Type == numericType)
                {
                    return true;
                }
            }

            return false;
        }
    }
}